import './globals.css'
import './global-styles.scss'
import { Inter } from 'next/font/google'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
      <body className={inter.className}>{children}</body>
      <Script src='https://eligibility.clan.africa/assets/scripts/client.js' />
    </html>
  )
}
