export const LocationData =[
    {label: "Abule Egba", value: "Abule Egba"},
    {label: "Agbara", value: "Agbara"},
    {label: "Agege", value: "Agege"},
    {label: "AJAO ESTATE", value: "AJAO ESTATE"},
    {label: "AMUWO", value: "AMUWO"},
    {label: "ANTHONY VILLAGE", value: "ANTHONY VILLAGE"},
    {label: "Apapa", value: "Apapa"},
    {label: "Badagry", value: "Badagry"},
    {label: "BERGER", value: "BERGER"},
    {label: "Coker", value: "Coker"},
    {label: "Doyin", value: "Doyin"},
    {label: "Ejigbo", value: "Ejigbo"},
    {label: "EPE", value: "EPE"},
    {label: "Fagba-Iju", value: "Fagba-Iju"},
    {label: "FESTAC", value: "FESTAC"},
    {label: "Gbagada", value: "Gbagada"},
    {label: "Ibeju Lekki", value: "Ibeju Lekki"},
    {label: "IGANDO", value: "IGANDO"},
    {label: "IJANIKIN", value: "IJANIKIN"},
    {label: "IJEGUN", value: "IJEGUN"},
    {label: "IJORA", value: "IJORA"},
    {label: "Ikeja", value: "Ikeja"},
    {label: "IKORODU", value: "IKORODU"},
    {label: "IKOTA", value: "IKOTA"},
    {label: "IKOTUN", value: "IKOTUN"},
    {label: "Ikoyi", value: "Ikoyi"},
    {label: "ILAJE-BARIGA", value: "ILAJE-BARIGA"},
    {label: "ILUPEJU", value: "ILUPEJU"},
    {label: "ISHERI", value: "ISHERI"},
    {label: "ISOLO", value: "ISOLO"},
    {label: "IYANA IBA", value: "IYANA IBA"},
    {label: "Iyana Ipaja", value: "Iyana Ipaja"},
    {label: "JAKANDE", value: "JAKANDE"},
    {label: "Ketu", value: "Ketu"},
    {label: "Lagos Island", value: "Lagos Island"},
    {label: "LAKOWE", value: "LAKOWE"},
    {label: "LEKKI", value: "LEKKI"},
    {label: "Magboro", value: "Magboro"},
    {label: "MARYLAND-ONIGBONGBO", value: "MARYLAND-ONIGBONGBO"},
    {label: "MEBANMU", value: "MEBANMU"},
    {label: "MILE 12", value: "MILE 12"},
    {label: "MILE 2", value: "MILE 2"},
    {label: "Mushin", value: "Mushin"},
    {label: "Ogba", value: "Ogba"},
    {label: "OGUDU", value: "OGUDU"},
    {label: "OJO", value: "OJO"},
    {label: "OJODU", value: "OJODU"},
    {label: "OJOTA", value: "OJOTA"},
    {label: "OKOKOMAIKO", value: "OKOKOMAIKO"},
    {label: "OKOTA", value: "OKOTA"},
    {label: "OREGUN", value: "OREGUN"},
    {label: "ORILE", value: "ORILE"},
    {label: "OSAPA-LEKKI", value: "OSAPA-LEKKI"},
    {label: "OSHODI", value: "OSHODI"},
    {label: "Palmgrove-Onipanu", value: "Palmgrove-Onipanu"},
    {label: "Satelite-Town", value: "Satelite-Town"},
    {label: "SOMOLU", value: "SOMOLU"},
    {label: "Surulere", value: "Surulere"},
    {label: "VI", value: "VI"},
    {label: "Yaba", value: "Yaba"},
]